#!/usr/bin/env python3
"""Generate OpenPBR per-parameter golden sweep fixtures (one sphere each).

Emits, under tests/golden-tests-data/, one `<name>/{fixture.usda,
regression.json}` per (parameter, value) case below — a sphere bound to a
MaterialX `open_pbr_surface` shader that authors exactly one swept input over
an OpenPBR-default base, lit by a uniform white dome. The golden CMake GLOB
(tests/integration/CMakeLists.txt) auto-registers each as `Golden.<name>` on
reconfigure; baselines are produced by `python _tools/run_goldens.py --rebake`.

These exist so EVERY OpenPBR lobe/parameter the renderer supports has a named,
byte-equal regression lock on a sphere — change a closure in
openpbr_material.slang and the exact affected sweeps light up. The white-furnace
block additionally locks the energy-conservation configs from OpenPBR v1.1.1
§"White furnace testing".

Run:  python _tools/gen_openpbr_golden_sweeps.py            # write fixtures
      python _tools/gen_openpbr_golden_sweeps.py --list     # names only
      python _tools/gen_openpbr_golden_sweeps.py --clean     # remove generated

Idempotent: every generated dir carries a marker line; --clean removes exactly
those, never a hand-authored fixture.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "tests" / "golden-tests-data"
MARKER = "GENERATED by _tools/gen_openpbr_golden_sweeps.py"

# Shared scene shell: a 0.7 m sphere at (0,1,0), a 35 mm camera at (0,1.4,3),
# and a uniform white dome (intensity 1.0). Only the shader inputs vary.
_HEADER = """#usda 1.0
(
    defaultPrim = "World"
    metersPerUnit = 1
    upAxis = "Y"
    doc = "{doc}"
)

def Xform "World"
{{
    def Sphere "Sphere" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {{
        double radius = 0.7
        double3 xformOp:translate = (0, 1, 0)
        uniform token[] xformOpOrder = ["xformOp:translate"]
        rel material:binding = </World/Materials/M>
    }}

    def Scope "Materials"
    {{
        def Material "M"
        {{
            token outputs:surface.connect = </World/Materials/M/Surface.outputs:surface>

            def Shader "Surface"
            {{
                uniform token info:id = "ND_open_pbr_surface_surfaceshader"
{inputs}
                token outputs:surface
            }}
        }}
    }}

    def Camera "Camera"
    {{
        float focalLength = 35.0
        float horizontalAperture = 36.0
        float verticalAperture = 20.25
        float2 clippingRange = (0.1, 1000)
        double3 xformOp:translate = (0, 1.4, 3)
        uniform token[] xformOpOrder = ["xformOp:translate"]
    }}

    def DomeLight "DomeLight"
    {{
        color3f inputs:color = (1, 1, 1)
        float inputs:intensity = {dome}
    }}
}}
"""


def _fmt(value) -> str:
    if isinstance(value, tuple):
        return "(" + ", ".join(f"{v:g}" for v in value) + ")"
    if isinstance(value, bool):
        return "1" if value else "0"
    return f"{value:g}"


def _input_line(name: str, value) -> str:
    if isinstance(value, tuple):
        ty = "color3f"
    elif isinstance(value, bool):
        ty = "bool"
    else:
        ty = "float"
    return f"                {ty} inputs:{name} = {_fmt(value)}"


# An OpenPBR-default-ish neutral dielectric base every sweep starts from; each
# case overrides a subset. (We author explicitly rather than rely on the ND
# defaults so the fixture is self-describing.)
BASE = {
    "base_color": (0.5, 0.5, 0.5),
    "base_weight": 1.0,
    "base_metalness": 0.0,
    "specular_weight": 1.0,
    "specular_roughness": 0.3,
    "specular_ior": 1.5,
}


def case(name: str, doc: str, overrides: dict, dome: float = 1.0) -> tuple[str, str, str]:
    inputs = dict(BASE)
    inputs.update(overrides)
    body = "\n".join(_input_line(k, v) for k, v in inputs.items())
    usda = _HEADER.format(doc=doc.replace('"', "'"), inputs=body, dome=_fmt(dome))
    reg = (
        '{ "$comment": "%s. OpenPBR sweep golden (sphere) — pixel-equal." }\n'
        % MARKER
    )
    return name, usda, reg


def build_cases() -> list[tuple[str, str, str]]:
    out: list[tuple[str, str, str]] = []

    # base_metalness sweep (white base so the metal F82 response is clean).
    for m in (0.0, 0.25, 0.5, 0.75, 1.0):
        out.append(case(
            f"openpbr_base_metalness_{int(m*100):03d}",
            f"OpenPBR base_metalness={m} (white base).",
            {"base_color": (1, 1, 1), "base_metalness": m, "specular_roughness": 0.25}))

    # base_color albedo check (dielectric).
    for tag, c in (("red", (0.8, 0.1, 0.1)), ("green", (0.1, 0.8, 0.1)),
                   ("blue", (0.1, 0.1, 0.8))):
        out.append(case(f"openpbr_base_color_{tag}",
                        f"OpenPBR base_color={tag} dielectric.", {"base_color": c}))

    # base_diffuse_roughness (EON).
    for r in (0.0, 0.5, 1.0):
        out.append(case(
            f"openpbr_base_diffuse_roughness_{int(r*100):03d}",
            f"OpenPBR base_diffuse_roughness={r} (EON energy-preserving Oren-Nayar).",
            {"base_color": (0.6, 0.5, 0.4), "base_diffuse_roughness": r}))

    # specular_weight (0..2).
    for w in (0.0, 0.5, 1.0, 2.0):
        out.append(case(
            f"openpbr_specular_weight_{int(w*100):03d}",
            f"OpenPBR specular_weight={w} (xi modulated dielectric reflectance).",
            {"specular_weight": w, "specular_roughness": 0.1}))

    # specular_color edge tint.
    out.append(case("openpbr_specular_color_tint",
                    "OpenPBR specular_color warm tint (top-side dielectric reflection).",
                    {"specular_color": (1.0, 0.7, 0.4), "specular_roughness": 0.1}))

    # specular_roughness sweep.
    for r in (0.0, 0.1, 0.3, 0.6, 1.0):
        out.append(case(
            f"openpbr_specular_roughness_{int(r*100):03d}",
            f"OpenPBR specular_roughness={r}.",
            {"base_color": (0.3, 0.3, 0.35), "specular_roughness": r}))

    # specular_ior sweep (exact dielectric Fresnel).
    for ior in (1.2, 1.33, 1.5, 1.8, 2.2):
        out.append(case(
            f"openpbr_specular_ior_{int(ior*100):03d}",
            f"OpenPBR specular_ior={ior} (exact F(mu,eta')).",
            {"base_color": (0.25, 0.25, 0.3), "specular_ior": ior,
             "specular_roughness": 0.1}))

    # specular anisotropy (needs a tangent frame; locks current behaviour).
    for a in (0.0, 0.5, 0.9):
        out.append(case(
            f"openpbr_specular_anisotropy_{int(a*100):03d}",
            f"OpenPBR specular_roughness_anisotropy={a} (metal).",
            {"base_color": (1, 1, 1), "base_metalness": 1.0,
             "specular_roughness": 0.4, "specular_roughness_anisotropy": a}))

    # transmission.
    for w in (0.0, 1.0):
        out.append(case(
            f"openpbr_transmission_weight_{int(w*100):03d}",
            f"OpenPBR transmission_weight={w} (white transmission_color, depth 0).",
            {"base_color": (0.8, 0.8, 0.8), "specular_roughness": 0.05,
             "transmission_weight": w}))
    out.append(case("openpbr_transmission_color_tint",
                    "OpenPBR transmission_color tint (transmission_weight 1).",
                    {"specular_roughness": 0.05, "transmission_weight": 1.0,
                     "transmission_color": (0.6, 0.9, 0.7)}))
    out.append(case("openpbr_transmission_thin_walled",
                    "OpenPBR transmission + geometry_thin_walled true.",
                    {"specular_roughness": 0.05, "transmission_weight": 1.0,
                     "transmission_color": (0.8, 0.85, 1.0),
                     "geometry_thin_walled": True}))

    # subsurface (diffuse fallback).
    for w in (0.0, 1.0):
        out.append(case(
            f"openpbr_subsurface_weight_{int(w*100):03d}",
            f"OpenPBR subsurface_weight={w} (subsurface_color as diffuse albedo).",
            {"subsurface_weight": w, "subsurface_color": (0.9, 0.5, 0.4)}))

    # coat weight / color / roughness / ior / darkening.
    for w in (0.0, 0.5, 1.0):
        out.append(case(
            f"openpbr_coat_weight_{int(w*100):03d}",
            f"OpenPBR coat_weight={w} over a coloured dielectric base.",
            {"base_color": (0.6, 0.15, 0.15), "coat_weight": w,
             "coat_roughness": 0.05}))
    out.append(case("openpbr_coat_color_tint",
                    "OpenPBR coat_color warm tint (coat_weight 1) — tints base + emission, not coat reflection.",
                    {"base_color": (0.6, 0.6, 0.6), "coat_weight": 1.0,
                     "coat_color": (1.0, 0.8, 0.55), "coat_roughness": 0.05}))
    for r in (0.0, 0.3, 0.6):
        out.append(case(
            f"openpbr_coat_roughness_{int(r*100):03d}",
            f"OpenPBR coat_roughness={r} (base-roughening of the specular lobe).",
            {"base_color": (0.2, 0.4, 0.6), "coat_weight": 1.0,
             "coat_roughness": r}))
    for ior in (1.3, 1.6, 2.0):
        out.append(case(
            f"openpbr_coat_ior_{int(ior*100):03d}",
            f"OpenPBR coat_ior={ior}.",
            {"base_color": (0.5, 0.5, 0.5), "coat_weight": 1.0,
             "coat_ior": ior, "coat_roughness": 0.05}))
    for d in (0.0, 0.5, 1.0):
        out.append(case(
            f"openpbr_coat_darkening_{int(d*100):03d}",
            f"OpenPBR coat_darkening={d} (interfaced-Lambertian Delta factor).",
            {"base_color": (0.7, 0.7, 0.7), "coat_weight": 1.0,
             "coat_darkening": d, "coat_roughness": 0.1}))

    # fuzz weight / color / roughness.
    for w in (0.0, 0.5, 1.0):
        out.append(case(
            f"openpbr_fuzz_weight_{int(w*100):03d}",
            f"OpenPBR fuzz_weight={w} (Zeltner LTC sheen over base).",
            {"base_color": (0.2, 0.2, 0.25), "fuzz_weight": w}))
    out.append(case("openpbr_fuzz_color_tint",
                    "OpenPBR fuzz_color tint (fuzz_weight 1) — fuzz albedo coloured, base transmittance gray.",
                    {"base_color": (0.15, 0.15, 0.15), "fuzz_weight": 1.0,
                     "fuzz_color": (0.9, 0.7, 0.8)}))
    for r in (0.1, 0.5, 1.0):
        out.append(case(
            f"openpbr_fuzz_roughness_{int(r*100):03d}",
            f"OpenPBR fuzz_roughness={r}.",
            {"base_color": (0.2, 0.2, 0.25), "fuzz_weight": 1.0,
             "fuzz_roughness": r}))

    # emission.
    for lum in (1.0, 10.0):
        out.append(case(
            f"openpbr_emission_luminance_{int(lum):03d}",
            f"OpenPBR emission_luminance={lum} nits (white emission_color).",
            {"base_color": (0.1, 0.1, 0.1), "emission_luminance": lum,
             "emission_color": (1, 1, 1)}))
    out.append(case("openpbr_emission_color_tint",
                    "OpenPBR emission_color tint at luminance 5.",
                    {"base_color": (0.1, 0.1, 0.1), "emission_luminance": 5.0,
                     "emission_color": (0.2, 0.6, 1.0)}))

    # --- white-furnace energy-conservation configs (§"White furnace testing") ---
    out.append(case("furnace_metal_white",
                    "White furnace: metal, white base+specular_color, metalness 1 — conductor energy lock.",
                    {"base_color": (1, 1, 1), "base_metalness": 1.0,
                     "specular_color": (1, 1, 1), "specular_roughness": 0.3}))
    out.append(case("furnace_dielectric_white",
                    "White furnace: dielectric, white base+specular_color — glossy-diffuse energy lock.",
                    {"base_color": (1, 1, 1), "specular_color": (1, 1, 1),
                     "specular_roughness": 0.3}))
    out.append(case("furnace_coat_white",
                    "White furnace: white coat over white dielectric base — coat must not add energy.",
                    {"base_color": (1, 1, 1), "specular_color": (1, 1, 1),
                     "coat_weight": 1.0, "coat_color": (1, 1, 1),
                     "coat_roughness": 0.3}))
    out.append(case("furnace_fuzz_white",
                    "White furnace: white fuzz over white dielectric base — gray transmittance, white albedo.",
                    {"base_color": (1, 1, 1), "specular_color": (1, 1, 1),
                     "fuzz_weight": 1.0, "fuzz_color": (1, 1, 1),
                     "fuzz_roughness": 0.5}))

    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="print fixture names and exit")
    ap.add_argument("--clean", action="store_true", help="remove generated fixtures and exit")
    args = ap.parse_args(argv)

    cases = build_cases()

    if args.list:
        for name, _, _ in cases:
            print(name)
        print(f"\n{len(cases)} fixtures", file=sys.stderr)
        return 0

    if args.clean:
        removed = 0
        for d in sorted(DATA_DIR.iterdir()):
            reg = d / "regression.json"
            if d.is_dir() and reg.exists() and MARKER in reg.read_text(encoding="utf-8"):
                for f in d.iterdir():
                    f.unlink()
                d.rmdir()
                removed += 1
        print(f"removed {removed} generated fixtures")
        return 0

    written = 0
    for name, usda, reg in cases:
        d = DATA_DIR / name
        d.mkdir(parents=True, exist_ok=True)
        (d / "fixture.usda").write_text(usda, encoding="utf-8")
        (d / "regression.json").write_text(reg, encoding="utf-8")
        written += 1
    print(f"wrote {written} OpenPBR sweep fixtures under {DATA_DIR}")
    print("next: reconfigure (registers Golden.openpbr_* / Golden.furnace_*), "
          "then python _tools/run_goldens.py --rebake")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
