#!/usr/bin/env python3
"""Pyxis perf-history dashboard (M10 — plan §35 / §36.6).

Renders a single self-contained HTML page from one or more KPI CSVs
emitted by ``_tools/run_regression.py``. The page is published as a
CI artifact each nightly run (§36.6 "Dashboard: a static HTML page
generated by _tools/perf_dashboard.py from the rolling CSV; published
as a CI artifact each nightly run. No external dashboard service v1.").

Usage:

    python perf_dashboard.py --csv tests/regression/m8_world_lobby/kpis.csv \\
                             --out perf_dashboard.html

    # Multiple fixtures collapsed into one tabbed page:
    python perf_dashboard.py --csv tests/regression/lobby/kpis.csv \\
                             --csv tests/regression/bistro/kpis.csv \\
                             --out perf_dashboard.html

Design rules:

    * **No external assets** — pure inline HTML + CSS + JS. The CI
      job uploads the .html file and viewers open it directly.
    * **No Plotly / D3 / etc.** — uses Chart.js loaded from
      ``cdn.jsdelivr.net`` (offline access is acceptable to render
      without charts; the data table still works in any browser).
    * **No heavy Python deps** — only ``csv`` + standard library, so
      Phase D runs in the same env as Phase B.
"""

from __future__ import annotations

import argparse
import csv
import datetime
import html
import json
import sys
from pathlib import Path
from typing import Any


# KPIs to chart on the dashboard. Tuple = (column, label, unit).
_TRACKED_KPIS: list[tuple[str, str, str]] = [
    ('pathtrace_gpu_p50_ms',         'pass.PathTrace p50',         'ms'),
    ('pathtrace_gpu_p99_ms',         'pass.PathTrace p99',         'ms'),
    ('commit_resources_cpu_p50_ms',  'commitResources p50',        'ms'),
    ('commit_resources_cpu_p99_ms',  'commitResources p99',        'ms'),
    ('frame_cpu_p50_ms',             'render.frame.cpu p50',       'ms'),
    ('frame_cpu_p99_ms',             'render.frame.cpu p99',       'ms'),
    ('wall_clock_ms',                'time-to-first-image (wall)', 'ms'),
    ('rmse',                         'image RMSE vs baseline',     ''),
]


def _read_csv(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open('r', newline='', encoding='utf-8-sig') as fh:
        return list(csv.DictReader(fh))


def _series_for(rows: list[dict[str, str]], column: str) -> list[dict[str, Any]]:
    """Build a chart-ready list of {x: timestamp, y: float} points,
    dropping rows where the metric isn't populated."""
    out: list[dict[str, Any]] = []
    for row in rows:
        raw = row.get(column, '')
        if raw is None or raw == '':
            continue
        try:
            value = float(raw)
        except (TypeError, ValueError):
            continue
        out.append({
            'x': row.get('timestamp_iso', ''),
            'y': value,
            'status': row.get('status', ''),
        })
    return out


def _fixture_payload(csv_path: Path) -> dict[str, Any]:
    rows = _read_csv(csv_path)
    fixture_name = rows[-1]['fixture'] if rows else csv_path.stem
    return {
        'name': fixture_name,
        'csv':  str(csv_path),
        'rows': len(rows),
        'latest_pyxis': rows[-1].get('pyxis_version', '') if rows else '',
        'latest_gpu':   rows[-1].get('gpu_name', '') if rows else '',
        'latest_status': rows[-1].get('status', '') if rows else '',
        'latest_timestamp': rows[-1].get('timestamp_iso', '') if rows else '',
        'series': {
            column: _series_for(rows, column)
            for column, _label, _unit in _TRACKED_KPIS
        },
        'rows_table': rows[-20:],  # last 20 runs in the bottom table
    }


_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Pyxis perf dashboard</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                       Oxygen, Ubuntu, Cantarell, sans-serif;
         margin: 0 auto; max-width: 1200px; padding: 24px;
         color: #1a1a1a; background: #f7f7f8; }
  h1 { font-size: 22px; margin: 0 0 16px 0; }
  .meta { color: #555; font-size: 13px; margin-bottom: 24px; }
  .tabs { display: flex; gap: 4px; margin-bottom: 16px; flex-wrap: wrap; }
  .tab  { padding: 6px 12px; border: 1px solid #d0d0d0; background: white;
          cursor: pointer; border-radius: 4px; font-size: 13px; }
  .tab.active { background: #1a1a1a; color: white; border-color: #1a1a1a; }
  .fixture { display: none; background: white; padding: 16px 20px;
             border-radius: 6px; box-shadow: 0 1px 4px rgba(0,0,0,0.05); }
  .fixture.active { display: block; }
  .fixture-meta { color: #555; font-size: 13px; margin-bottom: 12px; }
  .charts { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
  .chart-card { border: 1px solid #eaeaea; border-radius: 4px;
                padding: 12px; background: #fafafa; }
  .chart-title { font-size: 13px; font-weight: 600; margin-bottom: 8px; }
  .chart-canvas { height: 200px; }
  .runs-table { margin-top: 24px; }
  .runs-table table { border-collapse: collapse; width: 100%;
                      font-size: 12px; }
  .runs-table th, .runs-table td { border: 1px solid #e6e6e6;
                                    padding: 4px 8px; text-align: left;
                                    white-space: nowrap; }
  .runs-table th { background: #f0f0f0; }
  .status-pass { color: #1a7f37; }
  .status-fail { color: #d1242f; }
  .status-other { color: #9a6700; }
  .no-chart { color: #999; font-size: 12px; padding: 20px; text-align: center; }
</style>
</head>
<body>
<h1>Pyxis perf dashboard</h1>
<div class="meta">
  Generated __GENERATED_AT__ from __FIXTURE_COUNT__ fixture(s).
  Plan §35 / §36.6 — image-regression + per-test KPI history.
</div>
<div class="tabs">__TABS__</div>
<div id="fixtures">__FIXTURES__</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<script>
const PAYLOAD = __PAYLOAD__;
const KPIS    = __KPIS__;

function pickTab(idx) {
  document.querySelectorAll('.tab').forEach((el, i) =>
    el.classList.toggle('active', i === idx));
  document.querySelectorAll('.fixture').forEach((el, i) =>
    el.classList.toggle('active', i === idx));
}
document.querySelectorAll('.tab').forEach((el, idx) =>
  el.addEventListener('click', () => pickTab(idx)));
pickTab(0);

if (typeof Chart !== 'undefined') {
  PAYLOAD.forEach((fixture, fIdx) => {
    KPIS.forEach(kpi => {
      const data = fixture.series[kpi.column] || [];
      const canvas = document.getElementById(`chart_${fIdx}_${kpi.column}`);
      if (!canvas || data.length === 0) return;
      new Chart(canvas, {
        type: 'line',
        data: {
          datasets: [{
            label: kpi.label,
            data: data.map(p => ({x: p.x, y: p.y})),
            borderColor: '#1a1a1a',
            backgroundColor: 'rgba(26,26,26,0.08)',
            tension: 0.2,
            pointRadius: 3,
          }],
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          scales: {
            x: { type: 'time', time: { unit: 'day' },
                 ticks: { maxTicksLimit: 6, font: { size: 10 } } },
            y: { ticks: { font: { size: 10 } } },
          },
          plugins: { legend: { display: false } },
        },
      });
    });
  });
}
</script>
</body>
</html>
"""


def _render(payloads: list[dict[str, Any]]) -> str:
    tabs_html = ''.join(
        f'<div class="tab">{html.escape(p["name"])}</div>'
        for p in payloads
    )

    fixture_blocks = []
    for f_idx, payload in enumerate(payloads):
        charts = []
        for column, label, unit in _TRACKED_KPIS:
            unit_suffix = f' ({unit})' if unit else ''
            chart_id = f'chart_{f_idx}_{column}'
            has_data = bool(payload['series'].get(column))
            if has_data:
                body = f'<canvas id="{chart_id}" class="chart-canvas"></canvas>'
            else:
                body = '<div class="no-chart">no samples yet</div>'
            charts.append(
                f'<div class="chart-card">'
                f'<div class="chart-title">{html.escape(label)}{unit_suffix}</div>'
                f'{body}'
                f'</div>'
            )

        table_rows = []
        for row in payload['rows_table']:
            status = row.get('status', '')
            status_class = ('status-pass' if status == 'pass'
                            else 'status-fail' if status == 'fail'
                            else 'status-other')
            cells = [
                row.get('timestamp_iso', ''),
                f'<span class="{status_class}">{html.escape(status)}</span>',
                row.get('pyxis_git_sha', '')[:10],
                row.get('pathtrace_gpu_p50_ms', ''),
                row.get('pathtrace_gpu_p99_ms', ''),
                row.get('commit_resources_cpu_p50_ms', ''),
                row.get('frame_cpu_p50_ms', ''),
                row.get('wall_clock_ms', ''),
                row.get('rmse', ''),
            ]
            table_rows.append('<tr>' + ''.join(
                f'<td>{c if "<span" in str(c) else html.escape(str(c))}</td>'
                for c in cells) + '</tr>')

        table_html = f"""
            <div class="runs-table">
              <table>
                <thead><tr>
                  <th>timestamp</th><th>status</th><th>sha</th>
                  <th>PT p50 (ms)</th><th>PT p99 (ms)</th>
                  <th>commit p50 (ms)</th><th>frame cpu p50 (ms)</th>
                  <th>wall (ms)</th><th>rmse</th>
                </tr></thead>
                <tbody>{''.join(table_rows)}</tbody>
              </table>
            </div>"""

        fixture_blocks.append(
            f'<div class="fixture">'
            f'<div class="fixture-meta">'
            f'  {payload["rows"]} runs · latest pyxis '
            f'  <code>{html.escape(payload["latest_pyxis"][:60])}</code> · '
            f'  gpu <code>{html.escape(payload["latest_gpu"])}</code> · '
            f'  status <code>{html.escape(payload["latest_status"])}</code> · '
            f'  csv <code>{html.escape(payload["csv"])}</code>'
            f'</div>'
            f'<div class="charts">{"".join(charts)}</div>'
            f'{table_html}'
            f'</div>'
        )

    return (_HTML_TEMPLATE
            .replace('__GENERATED_AT__',
                     datetime.datetime.now(datetime.timezone.utc)
                             .replace(microsecond=0).isoformat())
            .replace('__FIXTURE_COUNT__', str(len(payloads)))
            .replace('__TABS__', tabs_html)
            .replace('__FIXTURES__', ''.join(fixture_blocks))
            .replace('__PAYLOAD__', json.dumps(payloads))
            .replace('__KPIS__', json.dumps(
                [{'column': c, 'label': l, 'unit': u}
                 for c, l, u in _TRACKED_KPIS])))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--csv', type=Path, action='append', required=True,
                        help='Per-fixture KPI CSV. Pass once per fixture; tabs '
                             'in the rendered page collapse them.')
    parser.add_argument('--out', type=Path, required=True,
                        help='Output HTML path.')
    args = parser.parse_args(argv)

    payloads = []
    for csv_path in args.csv:
        if not csv_path.exists():
            print(f'ERROR: CSV not found at {csv_path}', file=sys.stderr)
            return 2
        try:
            payloads.append(_fixture_payload(csv_path))
        except (OSError, csv.Error) as exc:
            print(f'ERROR: failed to parse {csv_path}: {exc}', file=sys.stderr)
            return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(_render(payloads), encoding='utf-8')
    print(f'wrote {args.out} ({args.out.stat().st_size:,} bytes, '
          f'{len(payloads)} fixture(s))')
    return 0


if __name__ == '__main__':
    sys.exit(main())
