# RFC 0004 — one-shot Omniverse SDK setup for building the Pyxis Hydra delegate.
#
# A clean clone of Pyxis CANNOT build the Kit extension on its own: nv-usd 25.11
# and Python 3.12 are multi-GB, license-gated, and live on NVIDIA's Packman feed
# (never vendored in-repo). This script acquires them non-interactively and
# writes the paths the CMake build needs. Run ONCE per machine.
#
#   pwsh _tools/omniverse/setup.ps1 [-ExternalDir D:\pyxis_external]
#
# Steps:
#   1. Clone kit-app-template (pinned) — provides Packman + the Kit kernel pin.
#   2. repo build once — bootstraps Packman + pulls Python 3.12 (+ kit kernel).
#   3. packman pull nv-usd 25.11 (deps/nv-usd.packman.xml) -> <ExternalDir>/usd-deps/usd.
#   4. Locate the Python 3.12 Packman pulled.
#   5. Write <ExternalDir>/usd-deps/paths.ps1 with PXR_USD_ROOT + PYTHON_ROOT.

[CmdletBinding()]
param(
    [string]$ExternalDir = "D:\pyxis_external",
    [string]$KitTemplateTag = "main"  # pin to a release tag for full reproducibility
)
$ErrorActionPreference = "Stop"
$repoRoot   = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)   # _tools/omniverse -> repo root
$kitDir     = Join-Path $ExternalDir "kit-app-template"
$usdDepsDir = Join-Path $ExternalDir "usd-deps"
$usdRoot    = Join-Path $usdDepsDir "usd"

New-Item -ItemType Directory -Force -Path $ExternalDir | Out-Null

# 1. Clone kit-app-template (for Packman + the Kit 110 version pins).
if (-not (Test-Path (Join-Path $kitDir "repo.bat"))) {
    Write-Host "[setup] Cloning kit-app-template ($KitTemplateTag)..."
    git clone --depth 1 --branch $KitTemplateTag `
        https://github.com/NVIDIA-Omniverse/kit-app-template.git $kitDir
} else {
    Write-Host "[setup] kit-app-template already present at $kitDir"
}

# 2. Bootstrap Packman + pull Python 3.12 (and the kit kernel) via a repo build.
Write-Host "[setup] Bootstrapping Packman + Kit kernel (repo build, multi-GB, one-time)..."
& (Join-Path $kitDir "repo.bat") build --config release | Out-Host

# 3. Pull nv-usd 25.11 (non-interactive — no template wizard needed).
Write-Host "[setup] Pulling nv-usd 25.11 dev via Packman..."
$packman = Join-Path $kitDir "tools\packman\packman.cmd"
$usdXml  = Join-Path $repoRoot "_tools\omniverse\deps\nv-usd.packman.xml"
& $packman pull $usdXml --platform windows-x86_64 -t "OUTDIR=$usdDepsDir" | Out-Host
if (-not (Test-Path (Join-Path $usdRoot "include\pxr\pxr.h"))) {
    throw "nv-usd pull did not produce $usdRoot\include\pxr\pxr.h"
}

# 4. Locate the Python 3.12 Packman pulled (newest 3.12.* in the cache).
$pmRoot = $env:PM_PACKAGES_ROOT; if (-not $pmRoot) { $pmRoot = "D:\packman-repo" }
$pyRoot = Get-ChildItem (Join-Path $pmRoot "chk\python") -Directory -ErrorAction SilentlyContinue |
          Where-Object { $_.Name -like "3.12.*" } |
          Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty FullName
if (-not $pyRoot -or -not (Test-Path (Join-Path $pyRoot "include\pyconfig.h"))) {
    throw "Python 3.12 (with pyconfig.h) not found under $pmRoot\chk\python"
}

# 5. Emit the paths the build script + CMake consume.
$paths = @"
# Generated by _tools/omniverse/setup.ps1 — paths to the pulled Kit SDK deps.
`$PXR_USD_ROOT = "$($usdRoot -replace '\\','/')"
`$PYTHON_ROOT  = "$($pyRoot  -replace '\\','/')"
"@
$pathsFile = Join-Path $usdDepsDir "paths.ps1"
Set-Content -Path $pathsFile -Value $paths -Encoding utf8

Write-Host ""
Write-Host "[setup] DONE." -ForegroundColor Green
Write-Host "  nv-usd 25.11 : $usdRoot"
Write-Host "  python 3.12  : $pyRoot"
Write-Host "  paths file   : $pathsFile"
Write-Host "Next: pwsh _tools/omniverse/build.ps1"
