# RFC 0004 — one-shot Omniverse SDK setup for building the Pyxis Hydra delegate.
#
# A clean clone of Pyxis CANNOT build the Kit extension on its own: nv-usd 25.11
# and Python 3.12 are multi-GB, license-gated, and live on NVIDIA's Packman feed
# (never vendored in-repo). This script acquires them non-interactively, ALL
# under <repo>/build/omniverse (gitignored) — no sibling external folder. Run
# ONCE per machine.
#
#   pwsh _tools/omniverse/setup.ps1
#
# Layout it produces (all under <repo>/build/omniverse):
#   kit-app-template/   the Kit SDK clone (provides Packman + the version pins)
#   packman/            the Packman package cache (PM_PACKAGES_ROOT)
#   usd-deps/usd        nv-usd 25.11 dev (headers + import libs)
#   usd-deps/paths.ps1  PXR_USD_ROOT + PYTHON_ROOT for build.ps1 / run_smoke.ps1

[CmdletBinding()]
param([string]$KitTemplateTag = "main")  # pin to a release tag for full reproducibility
$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)   # _tools/omniverse -> repo root
$omniDir  = Join-Path $repoRoot "build\omniverse"
$kitDir   = Join-Path $omniDir "kit-app-template"
$pmRoot   = Join-Path $omniDir "packman"
$usdDeps  = Join-Path $omniDir "usd-deps"
$usdRoot  = Join-Path $usdDeps "usd"

New-Item -ItemType Directory -Force -Path $omniDir, $pmRoot | Out-Null
# Self-contained Packman cache under the repo (no global folder).
$env:PM_PACKAGES_ROOT = $pmRoot

# 1. Clone kit-app-template (for Packman + the Kit 110 version pins).
if (-not (Test-Path (Join-Path $kitDir "repo.bat"))) {
    Write-Host "[setup] Cloning kit-app-template ($KitTemplateTag) into build/omniverse..."
    git clone --depth 1 --branch $KitTemplateTag `
        https://github.com/NVIDIA-Omniverse/kit-app-template.git $kitDir
} else {
    Write-Host "[setup] kit-app-template already present at $kitDir"
}

# 2. Bootstrap Packman + pull Python 3.12 (and the kit kernel) via a repo build.
Write-Host "[setup] Bootstrapping Packman + Kit kernel (repo build, multi-GB, one-time)..."
& (Join-Path $kitDir "repo.bat") build --config release | Out-Host

# 3. Pull nv-usd 25.11 (non-interactive — no template wizard needed).
Write-Host "[setup] Pulling nv-usd 25.11 dev via Packman -> $usdRoot ..."
$packman = Join-Path $kitDir "tools\packman\packman.cmd"
$usdXml  = Join-Path $repoRoot "_tools\omniverse\deps\nv-usd.packman.xml"
& $packman pull $usdXml --platform windows-x86_64 -t "OUTDIR=$usdDeps" | Out-Host
if (-not (Test-Path (Join-Path $usdRoot "include\pxr\pxr.h"))) {
    throw "nv-usd pull did not produce $usdRoot\include\pxr\pxr.h"
}

# 4. Locate the Python 3.12 Packman pulled (newest 3.12.* in the cache).
$pyRoot = Get-ChildItem (Join-Path $pmRoot "chk\python") -Directory -ErrorAction SilentlyContinue |
          Where-Object { $_.Name -like "3.12.*" } |
          Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty FullName
if (-not $pyRoot -or -not (Test-Path (Join-Path $pyRoot "include\pyconfig.h"))) {
    throw "Python 3.12 (with pyconfig.h) not found under $pmRoot\chk\python"
}

# 5. Emit the paths the build + run scripts consume.
$paths = @"
# Generated by _tools/omniverse/setup.ps1 — paths to the pulled Kit SDK deps.
`$PXR_USD_ROOT = "$($usdRoot -replace '\\','/')"
`$PYTHON_ROOT  = "$($pyRoot  -replace '\\','/')"
`$PM_PACKAGES_ROOT = "$($pmRoot -replace '\\','/')"
"@
$pathsFile = Join-Path $usdDeps "paths.ps1"
Set-Content -Path $pathsFile -Value $paths -Encoding utf8

Write-Host ""
Write-Host "[setup] DONE (all under build/omniverse)." -ForegroundColor Green
Write-Host "  nv-usd 25.11 : $usdRoot"
Write-Host "  python 3.12  : $pyRoot"
Write-Host "  packman cache: $pmRoot"
Write-Host "  paths file   : $pathsFile"
Write-Host "Next: pwsh _tools/omniverse/build.ps1"
