# Pyxis version-source emitter.
#
# Invoked by Version.cmake's add_custom_command. Resolves the current git SHA
# (best-effort; "unknown" if .git is absent or git is missing) and writes the
# Version.cpp source consumed by pyxis_renderer.dll.
#
# Required input variables:
#   PYXIS_VERSION_STRING            (e.g. "0.0.1")
#   PYXIS_VERSION_ENCODED_MAJOR     (integer)
#   PYXIS_VERSION_ENCODED_MINOR     (integer)
#   PYXIS_VERSION_ENCODED_PATCH     (integer)
#   PYXIS_VERSION_OUT               (absolute path to write Version.cpp to)
#   PYXIS_VERSION_REPO              (repo root)

set(_sha "unknown")
find_program(_git git)
if(_git)
    execute_process(
        COMMAND "${_git}" -C "${PYXIS_VERSION_REPO}" rev-parse HEAD
        OUTPUT_VARIABLE _shaRaw
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _shaRaw)
        set(_sha "${_shaRaw}")
    endif()
endif()

math(EXPR _encoded
    "(${PYXIS_VERSION_ENCODED_MAJOR} << 24) | (${PYXIS_VERSION_ENCODED_MINOR} << 16) | ${PYXIS_VERSION_ENCODED_PATCH}")

set(_contents "// Generated by _cmake/Version.write.cmake — do not edit by hand.
// Plan §22.2.

#include <Pyxis/Renderer/Version.h>

namespace pyxis {

namespace {
constexpr uint32_t    kEncoded = ${_encoded};
constexpr const char* kString  = \"${PYXIS_VERSION_STRING}+${_sha}\";
constexpr const char* kGitSha  = \"${_sha}\";
}  // namespace

uint32_t    GetVersionEncoded() noexcept { return kEncoded; }
const char* GetVersionString()  noexcept { return kString;  }
const char* GetVersionGitSha()  noexcept { return kGitSha;  }

}  // namespace pyxis
")

file(WRITE "${PYXIS_VERSION_OUT}" "${_contents}")
